course_i18n_path: "course.course_status."
max_first_name: 225
lessons_per_page: 5
course_per_page: 5
max_last_name: 225
max_password: 225
trcate_text: 100
text_length: 135
currency: 20_000
text_max: 20_000
size: "263x180"
min_password: 6
string_max: 250
trcate_name: 40
max_email: 225
page_limit: 8
condition: "1"
des_max: 180
limit: 8
en: en
vi: vi
i18n:
  picture: "56x50"
